# Nelmio CORS Configuration
nelmio_cors:
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['GET']
            max_age: 3600
            hosts: []
            origin_regex: false
