monolog:
    channels: ['rate_limit', 'denylist', 'crawler', 'main']
    handlers:
        rate_limit:
            # log all messages (since debug is the lowest level)
            level: info
            type: stream
            path: '%kernel.logs_dir%/rate_limit.log'
            channels: [rate_limit]
        denylist:
            # log all messages (since debug is the lowest level)
            level: info
            type: stream
            path: '%kernel.logs_dir%/denylist.log'
            channels: ['denylist']
        crawler:
            level: info
            type: stream
            path: '%kernel.logs_dir%/crawler.log'
            channels: ['crawler']
        main:
            type: fingers_crossed
            action_level: critical
            handler: main_handler
            excluded_http_codes: [502]
        main_handler:
            type: group
            members: [console, log_file, mailer]
        console:
            type: console
            level: debug
            process_psr_3_messages: false
        log_file:
            type: stream
            level: info
            path: '%kernel.logs_dir%/%kernel.environment%.log'
        mailer:
            type: deduplication
            time: 300
            handler: symfony_mailer
        symfony_mailer:
            type: symfony_mailer
            level: critical
            from_email: '%env(MAILER_FROM_EMAIL)%'
            to_email: '%env(MAILER_TO_EMAIL)%'
            subject: '[XTools] Fatal error: %%message%%'
            formatter: monolog.formatter.html
            content_type: text/html
